<?php

const INIT_INFLUENCER_COUNT = 50;
const INIT_INFLUENCER_POST_MIN_COUNT = 10;
const INIT_INFLUENCER_POST_MAX_COUNT = 30;
const INIT_INFLUENCER_REPLY_MIN_COUNT = 5;
const INIT_INFLUENCER_REPLY_MAX_COUNT = 10;
const INIT_INFLUENCER_FOLLOW_MIN_COUNT = 3;
const INIT_INFLUENCER_FOLLOW_MAX_COUNT = 10;
