@startuml social-networking-service
title ユーザー認証のアクティビティ図

start

:ユーザーはSNSアプリを開く;

if (ログインしているか？) then (yes)
    if (メール検証済みか？) then (yes)
        :タイムラインを表示する;
    else (no)
        :メール検証待ち画面を表示する;
        end
    endif
else (no)
    :トレンドタイムラインとログインボタン、
    アカウント作成ボタンを表示する;

    if (アカウントを持っているか？) then (yes)
        :ユーザーはログインボタンをクリックする;
        :ログイン画面を表示する;

        if (パスワードを忘れたか？) then (yes)
            :ユーザーはパスワードリセットボタンをクリックする;
            :パスワードリセット画面を表示する;
            :ユーザーはメールアドレスを入力する;
            :入力されたメールアドレスにパスワード再設定用メールを送信する;
            :ユーザーはパスワード再設定用メール内のURLをクリックする;
            :パスワード再設定画面を表示する;
            :ユーザーは新しいパスワードを入力する;
            :ログイン画面を表示する;
        else (no)
        endif
        :ユーザーはログイン情報を入力する;
        :認証を行う;
    else (no)
        :ユーザーはアカウント作成ボタンをクリックする;
        :アカウント作成画面を表示する;
        :ユーザーはアカウント情報を入力する;
        :入力されたメールアドレスに検証メールを送信する;
        :ユーザーは検証メール内のURLをクリックする;
        :認証を行う;
    endif

    if (認証成功) then (yes)
        :タイムラインを表示する;
    else (no)
        :各画面でエラーメッセージ等を表示する;
        end
    endif
endif

:各種操作を行う;

stop
@enduml
