@startuml social-networking-service
title 状態遷移図

[*] --> トップ画面 : アプリ起動

state トップ画面 {
    [*] --> 初期状態

    初期状態 --> ユーザー登録画面
    初期状態 --> ログイン画面
    初期状態 --> タイムライン : ログイン完了後
}

state ユーザー登録画面 {
    [*] --> アカウント未登録状態

    アカウント未登録状態 --> 登録成功 : アカウント情報入力
    登録成功 --> メール検証待ち : 検証メール送信
    メール検証待ち --> 検証成功
    検証成功 --> タイムライン : ユーザー登録, ログイン完了
    メール検証待ち --> 検証失敗
    検証失敗 --> メール検証待ち
    アカウント未登録状態 --> 登録失敗 : アカウント情報入力
    登録失敗 --> アカウント未登録状態
}

state ログイン画面 {
    [*] --> 未ログイン状態

    未ログイン状態 --> ログイン成功 : ログイン情報入力, 認証成功
    ログイン成功 --> タイムライン : ログイン完了
    未ログイン状態 --> ログイン失敗 : ログイン情報入力, 認証失敗
    ログイン失敗 --> 未ログイン状態 : エラーメッセージを表示後
}

state タイムライン {
    [*] --> タイムライン表示中

    タイムライン表示中 --> タイムライン表示中 : メニューのホームアイコンをクリック
    タイムライン表示中 --> 投稿作成モーダル : メニュー新規投稿アイコンをクリック
    タイムライン表示中 --> プロフィール画面 : 投稿のプロフィールアイコン, もしくはメニューのプロフィールアイコンをクリック
    タイムライン表示中 --> 投稿表示画面 : 投稿をクリック
    タイムライン表示中 --> メッセージ画面 : メニューのメッセージアイコンをクリック
    タイムライン表示中 --> 通知画面 : メニューの通知アイコンをクリック
    タイムライン表示中 --> ログアウト : メニューのログアウトをクリック
}

state 投稿作成モーダル {
    [*] --> 投稿作成中

    投稿作成中 --> 投稿作成完了 : 投稿完了
    投稿作成中 --> 投稿保存中 : 下書き保存
    投稿保存中 --> 削除 : 下書き削除
    投稿保存中 --> 投稿作成完了 : 下書き投稿を投稿作成完了
    投稿作成中 --> 投稿待ち : 投稿をスケジューリング
    投稿待ち --> 削除 : スケジューリングされた投稿削除
    投稿待ち --> 投稿作成完了 : スケジューリング投稿完了
}

state プロフィール画面 {
    [*] --> プロフィール表示中

    プロフィール表示中 --> プロフィール編集中 : 編集ボタンをクリック
    プロフィール編集中 --> プロフィール表示中 : 編集完了
    プロフィール表示中 --> 投稿表示画面 : 投稿をクリック
}

state 投稿表示画面 {
    [*] --> 投稿表示中

    投稿表示中 --> プロフィール画面 : 投稿のプロフィールアイコンをクリック
}

state メッセージ画面 {
    [*] --> メッセージ一覧表示中

    メッセージ一覧表示中 --> メッセージ画面表示中 : 一覧から特定のユーザーをクリック
    メッセージ画面表示中 --> メッセージ一覧表示中 : 戻るアイコンをクリック
    メッセージ一覧表示中 --> プロフィール画面 : ユーザーのプロフィールアイコンをクリック
}

state 通知画面 {
    [*] --> 通知一覧表示中

    通知一覧表示中 --> 投稿表示画面 : 投稿関連のお知らせのケース
    通知一覧表示中 --> メッセージ画面 : メッセージ関連のお知らせのケース
    通知一覧表示中 --> プロフィール画面 : プロフィール関連のお知らせのケース
    通知一覧表示中 --> プロフィール画面 : ユーザーのプロフィールアイコンをクリック
}

state ログアウト {
    [*] --> 初期状態
}
@enduml
